header:
  license:
    spdx-id: CC-BY-4.0
    copyright-owner: The Newton Developers

    content: |
      SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
      SPDX-License-Identifier: CC-BY-4.0

    # Pattern is matched against lowercased text where "(c)" is normalized
    # to the word "copyright", so "Copyright (c)" becomes "copyright copyright".
    pattern: |
      spdx-filecopyrighttext: copyright copyright \d{4} the newton developers
      spdx-license-identifier: cc-by-4\.0

  paths:
    - "**/*.rst"

  paths-ignore:
    - "docs/api/_generated/**"
    - "docs/_templates/**"

  language:
    reStructuredText:
      extensions:
        - ".rst"
      comment_style_id: DoubleDot

  comment: on-failure
